import type { Portfolio } from './types';

const portfolioData: Portfolio = {
  personal: {
    name: 'Aadityaamlan Panda',
    also_known_as: 'Aaditya Amlan Panda',
    date_of_birth: 'August 15',
    hometown: 'Sambalpur, Odisha, India',
    current_location: 'IIT Kanpur, Kanpur, Uttar Pradesh, India',
    phone: '+91-8093756736',
    email: {
      academic: 'aadityaap22@iitk.ac.in',
      personal: 'aadityaamlanpanda@gmail.com',
    },
    links: {
      portfolio: 'https://aadityaamlan-panda.github.io/Aadityaamlan-Panda/',
      github: 'https://github.com/Aadityaamlan-Panda',
      linkedin: 'https://www.linkedin.com/in/aadityaap22',
      leetcode: 'https://leetcode.com/u/aadityaap22/',
    },
    headline:
      'Final Year Undergraduate, Chemical Engineering @ IIT Kanpur | ML & Process Design | Academic Excellence Awardee | Ex-Intern @ Infinity Learn | Weightlifting Trainee | Poet, Author, Translator',
    tagline:
      'Building things that make invisible systems legible — from RAG pipelines that explain every retrieval decision, to VR rooms that teach thermodynamics through memory.',
    typewriter_options: [
      'I build transparent AI systems, industrial process simulations, and immersive XR experiences.',
      'From hybrid RAG pipelines to Meta Quest VR — engineering at the intersection of AI, chemistry, and creativity.',
      'Final-year ChE at IIT Kanpur. CGPA 9.41. Researcher. Engineer. Poet.',
    ],
    bio_short:
      'Final-year Chemical Engineering undergraduate at IIT Kanpur (CPI 9.41/10). I build production-quality AI/ML systems, XR learning applications, and industrial process simulations. My work spans hybrid RAG pipelines, Meta Quest VR apps, Spring Boot backends, and Aspen Plus process design — all with a bias toward transparency, rigorous testing, and measurable results. Ajai Agarwal Memorial Prize recipient. Published poet across 10 international anthologies. Competitive weightlifter, Inter-IIT representative. From Sambalpur, Odisha.',
    bio_long:
      'I am a final-year Chemical Engineering undergraduate at IIT Kanpur with a CPI of 9.41/10 — recipient of the Ajai Agarwal Memorial Prize, awarded by the IIT Kanpur Director to the best fourth-year student in Chemical Engineering, and a three-time Academic Excellence Award winner. I grew up in Sambalpur, Odisha, and arrived at IIT Kanpur in 2022 after securing All India Rank 4429 in JEE Advanced among over 200,000 qualified candidates. What followed was four years of building things across an unusually wide range — production-quality RAG systems, Meta Quest VR applications, Spring Boot REST APIs, industrial plant simulations in Aspen Plus, macroeconomic data pipelines, and multilingual video dubbing tools. My flagship project, Traceable Fusion RAG for Algorithms, is a transparency-first retrieval-augmented generation pipeline that indexes roughly 1 GB of open-source algorithm code and exposes every retrieval score, reranking decision, and confidence signal in a live terminal UI. My second flagship, VR Memory Palace — Chemical Engineering Edition, encodes 114 ChE concepts in a navigable Meta Quest apartment using the Method of Loci. A pilot study showed a 7.7 pp gain in quiz accuracy and 60.8% faster response times. Before all of this, I was a Student Mentor Intern at Infinity Learn, where I built 18 functional prototypes and enabled 30+ hackathon teams. Outside engineering, I am a published poet and author — co-published across 10 international literary anthologies, ranked 7th globally at the Storymirror World Writing Championship 2023, and the sole Odia-to-English literary translator in Matruakshar International Journal Vol. I. I also lift weights competitively, having won silver at the Udghosh 2024 under-77 kg category and represented IIT Kanpur at the 56th and 57th Inter-IIT Sports Meets.',
    languages: [
      { language: 'English', proficiency: 'Professional working proficiency' },
      { language: 'Odia', proficiency: 'Native / bilingual' },
      { language: 'Hindi', proficiency: 'Native / bilingual' },
      { language: 'Middle English (1100–1500)', proficiency: 'Limited working proficiency' },
    ],
    interests: [
      'Weightlifting / Olympic Lifting / Powerlifting',
      'SpeedCubing',
      'Geopolitics',
      'Literature',
      'Nature Observation',
      'Poetry',
      'Creative Writing',
    ],
    availability: 'Open to full-time SDE, AI/ML, and research roles starting May/June 2026.',
    notable_quote:
      'Words are the bridges between souls, and through them, we traverse the infinite landscapes of human experience.',
  },

  education: [
    {
      institution: 'Indian Institute of Technology Kanpur',
      degree: 'B.Tech',
      field: 'Chemical Engineering',
      minor: 'Economic Sciences',
      period: 'Oct 2022 – May 2026',
      gpa: '9.41/10',
      location: 'Kanpur, Uttar Pradesh, India',
      activities: [
        'Weightlifting Team',
        'Secretary, UG Academics (AnC Council)',
        'WebD Projects',
        'Udghosh',
        'Takneek',
        'Inferno',
      ],
      relevant_courses: {
        mathematics: [
          'Real Analysis',
          'Several Variable Calculus',
          'Ordinary Differential Equations',
          'Applied Probability & Statistics',
        ],
        computing: ['Intro to Machine Learning', 'Computational Methods', 'Linear Algebra'],
        chemical_engineering: [
          'ChE Thermodynamics',
          'Transport Phenomena',
          'Fluid Mechanics',
          'Mass Transfer',
          'Heat Transfer',
          'Reaction Engineering',
          'Process Design',
          'Process Dynamics',
        ],
        economics: ['Microeconomics', 'Economics and Public Policy'],
      },
    },
    {
      institution: "St. Joseph's Convent Higher Secondary School",
      location: 'Sambalpur, Odisha',
      board_12th: 'ISC (XII)',
      score_12th: '97.25%',
      year_12th: '2022',
      board_10th: 'ICSE (X)',
      score_10th: '96.40%',
      year_10th: '2020',
    },
  ],

  experience: [
    {
      title: 'Student Mentor Intern',
      company: 'Infinity Learn (Rankguru Technology Solutions Pvt. Ltd.)',
      linkedin_title: 'Student Mentor | Full Stack | AI | Automation',
      period: 'Oct 2024 – Jan 2025',
      location: 'Hyderabad, Telangana, India',
      highlights: [
        'Integrated Cohere API and 10 Microsoft Azure APIs into prototypes, engineering modular prompt flows',
        'Built 8 Python + HTML/CSS/JS lightweight functional models; achieved 60% less frontend complexity',
        'Developed 5 OpenCV + MediaPipe pipelines for real-time frame capture and live inference',
        'Prepared 12+ problem statements and 18 working prototypes driving 15+ school innovation initiatives',
        'Enabled 30+ teams to redesign and amplify solutions through structured hackathon delivery',
      ],
      impact_metrics: {
        prototypes_built: 18,
        problem_statements: '12+',
        hackathon_teams_enabled: '30+',
        frontend_complexity_reduction: '60%',
      },
    },
  ],

  skills: {
    programming_languages: ['C', 'C++', 'Python', 'Java', 'C#', 'SQL', 'Fortran', 'HTML', 'CSS', 'JavaScript'],
    ai_ml_data_science: [
      'LangChain', 'ChromaDB', 'BM25', 'Cohere (Embed + Rerank)', 'RAGAS',
      'scikit-learn', 'NumPy', 'Pandas', 'Matplotlib', 'OpenCV', 'MediaPipe',
      'FinBERT', 'Random Forest', 'SVM (LinearSVC)', 'TensorFlow',
      'NLTK', 'NetworkX', 'PyVis', 'TF-IDF', 'PageRank', 'Groq API', 'Ollama',
    ],
    backend_apis: [
      'Spring Boot 3.5', 'Java 21', 'Maven', 'PostgreSQL', 'Neon',
      'Spring Data JPA', 'REST API Design', 'pytest', 'Microsoft Azure APIs', 'Cohere Chat API',
    ],
    frontend_web: ['Streamlit', 'Tkinter', 'Vanilla HTML/CSS/JS', 'PyVis Interactive Networks'],
    xr_game_3d: ['Unity 6 (URP 17.3.0)', 'C#', 'Meta Quest SDK v85.0.0', 'OpenXR 1.16.1', 'WebGL Builds'],
    chemical_engineering_tools: [
      'Aspen Plus', 'Aspen EDR',
      'MATLAB (ode45, bvp4c, pdepe, fmincon)', 'Simulink',
      'Ziegler-Nichols', 'Tyreus-Luyben', 'Pinch Analysis', 'UNIQUAC Thermodynamics',
    ],
    audio_video: ['PyDub', 'FFmpeg', 'SpeechRecognition', 'gTTS', 'deep-translator', 'pygame', 'yt-dlp'],
    devops_tools: ['Git', 'GitHub', 'LaTeX', 'Ubuntu Linux', 'FRED API', 'pytest', 'Docker', 'GitHub Pages', 'Streamlit Community Cloud'],
  },

  projects: [
    {
      id: '01',
      tier: 'flagship',
      name: 'Traceable Fusion RAG for Algorithms',
      tagline:
        'A transparency-first RAG pipeline that answers algorithm questions grounded in ~1 GB of real open-source code — with every retrieval score, reranking decision, and confidence signal exposed in a live terminal UI.',
      one_liner: 'Most RAG systems give you answers. This one shows you exactly why it chose them.',
      category: ['AI', 'RAG', 'LLM Systems'],
      period: 'Apr 2026 – May 2026',
      team_size: 1,
      type: 'Solo · Open Source',
      role: 'Solo designer and developer — architecture, ingestion, retrieval, generation, guardrails, transparency layer, terminal UI, test suite, RAGAS evaluation.',
      problem:
        'RAG systems for code are notoriously opaque: users get an answer but have no visibility into why certain documents were retrieved, how confident the system is, or whether the LLM is hallucinating. Existing tools also struggle with multi-language codebases (C++, Python, Java, Markdown) where naïve text splitting destroys function-level semantics.',
      tech_stack: [
        'Python', 'ChromaDB', 'rank-bm25', 'LangChain',
        'Cohere embed-english-v3.0', 'Cohere Rerank API',
        'Groq Llama 3.3 70B', 'Cohere Command A+',
        'RAGAS', 'pytest', 'Rich', 'Textual', 'Pydantic BaseSettings',
      ],
      key_features: [
        'Hybrid BM25 + dense retrieval fused via Reciprocal Rank Fusion (RRF, k=60)',
        'Language-aware chunkers: brace-matched C++/Java, indent-tracked Python, heading-preserving Markdown',
        'Cross-encoder reranking with language-match metadata boost/penalty',
        'Multi-signal confidence scoring (retrieval, source verification, coverage)',
        'Confidence gate at 0.25 refuses rather than hallucinating',
        'Multi-provider LLM fallback with automatic failover on rate-limit detection',
        'Live terminal UI rendering step timings, scores, and confidence breakdowns',
        '40+ unit / integration / e2e tests; e2e runs in 68s with real API keys',
        'RAGAS evaluation suite with per-question metric breakdown',
      ],
      results: {
        ragas_context_precision: 0.87,
        ragas_context_recall: 0.75,
        ragas_faithfulness: 0.61,
        ragas_answer_relevancy: 0.60,
        unit_integration_tests_passing: 43,
        e2e_tests_passing: 4,
        e2e_runtime_seconds: 68,
        knowledge_base_size: '~1 GB',
        repos_ingested: 6,
        languages_indexed: ['C++', 'Python', 'Java', 'Markdown'],
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Traceable-Fusion-RAG-for-Algorithms',
      },
    },
    {
      id: '02',
      tier: 'flagship',
      name: 'VR Memory Palace — Chemical Engineering Edition',
      tagline:
        'A Meta Quest XR application encoding 114 Chemical Engineering concepts in a navigable virtual apartment via the Method of Loci — backed by a Spring Boot REST API, PostgreSQL, and a companion spaced-repetition web dashboard.',
      one_liner: 'What if your apartment could teach you Chemical Engineering thermodynamics? This one does.',
      category: ['XR', 'Full Stack', 'Research', 'EdTech'],
      period: { vr_build: 'Jan 2026 – May 2026', desktop_web_build: 'Mar 2026 – May 2026' },
      team_size: 2,
      team_members: ['Aadityaamlan Panda', 'Abhijit Dalai (IIT Kanpur ChE)'],
      role: 'Co-developer and researcher. Unity C# scripting, Spring Boot REST API design and backend deployment, spaced-repetition algorithm, pilot study design and analysis, LaTeX research paper authoring.',
      problem:
        'Undergraduate Chemical Engineering students struggle to retain abstract quantitative concepts using conventional flashcard or lecture review. Existing VR education tools rarely combine an explicit Method-of-Loci spatial encoding protocol with fully interactive VR for abstract technical undergraduate content.',
      tech_stack: {
        vr_client: ['Unity 6 (URP 17.3.0)', 'C#', 'Meta XR SDK v85.0.0', 'OpenXR 1.16.1'],
        backend: ['Spring Boot 3.5', 'Java 21', 'Maven 3.9'],
        database: 'PostgreSQL (Neon cloud, ap-southeast-1)',
        orm: 'Spring Data JPA / Hibernate',
        web_dashboard: 'Vanilla HTML/JS',
        quiz_analysis: ['Streamlit', 'Python (pandas, matplotlib)'],
        deployment: ['Render.com (Docker)', 'Neon (serverless Postgres)'],
        build_targets: ['WebGL (browser)', 'APK (Meta Quest)'],
      },
      key_features: [
        '114 ChE concepts spatially anchored to household objects with mnemonic logic',
        'Meta Quest controller bindings: double-click right trigger reveals floating concept labels and image panels',
        'Raycasting selection with green/white ray visual feedback',
        'Spring Boot REST API with 9 endpoints: paginated listing, keyword search, PATCH spaced-repetition scoring',
        'CSV offline fallback in Unity — activates transparently on network failure',
        'Web review dashboard with traffic-light Easy/Medium/Hard recall buttons',
        'Priority-sorted spaced-repetition: priority = strength − (repetitions × 0.5)',
        'XRSceneBuilder editor tool auto-wires interaction components on all 184 GameObjects',
      ],
      results: {
        pilot_study: {
          participants: 6,
          quiz_accuracy_round1: '72.8%',
          quiz_accuracy_round2: '80.5%',
          accuracy_gain_pp: '+7.7',
          response_time_r1_sec: 20.2,
          response_time_r2_sec: 7.9,
          response_time_reduction_pct: '60.8%',
          zero_hint_usage_in_r2: '3 of 5 participants',
          learning_efficacy_rating: '8.5/10',
          vr_aided_quiz_rating: '9.0/10',
        },
        concepts_encoded: 114,
        api_endpoints: 9,
        scene_gameobjects: 184,
        research_paper: 'Co-authored LaTeX research paper with 8 figures',
      },
      links: {
        github_desktop_web: 'https://github.com/Aadityaamlan-Panda/Memory-Palace-ChE-Desktop-Web',
        live_backend: 'https://memory-palace-server-render.onrender.com',
      },
    },
    {
      id: '03',
      tier: 'strong_sde',
      name: 'ML-Based Financial Risk Analytics Platform',
      tagline:
        'A production-ready Streamlit dashboard combining Random Forest trading signals with FinBERT news sentiment, Value at Risk, and regulatory compliance monitoring.',
      one_liner: 'One dashboard for trading signals, risk exposure, and regulatory compliance — something most open-source tools keep separate.',
      category: ['ML', 'FinTech', 'NLP'],
      period: 'Aug 2025 – Oct 2025',
      team_size: 1,
      type: 'Solo · Open Source',
      tech_stack: [
        'Python 3.9+', 'scikit-learn (RandomForestClassifier)', 'FinBERT',
        'Streamlit', 'yfinance', 'NewsAPI', 'Plotly', 'pandas', 'NumPy',
      ],
      key_features: [
        'Real-time BUY/SELL signal generation from engineered technical indicators and FinBERT news sentiment',
        'VaR (Value at Risk) and Sharpe Ratio risk dashboard',
        'Automated regulatory compliance monitoring with audit checks',
        'Feature importance explainability panel (Random Forest)',
        'Demo Mode using synthetic data — no API key required for demonstration',
        'Interactive Plotly charts with OHLCV overlays and signal annotations',
      ],
      results: {
        directional_accuracy: '>60% on real market data',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Stock-Prediction-VAR-Analysis',
      },
    },
    {
      id: '04',
      tier: 'strong_sde',
      name: 'QuerySynth',
      tagline:
        'A Tkinter desktop AI assistant combining local LLM inference (Ollama) with live multi-source retrieval — Wikipedia, arXiv, news, Wolfram Alpha, YouTube audio, code search — rendered in Markdown with threaded I/O.',
      one_liner: 'A fully local AI assistant that fetches only the sources it needs, when it needs them.',
      category: ['AI', 'Desktop App', 'RAG'],
      period: 'Jul 2025 – Aug 2025',
      team_size: 1,
      type: 'Solo · Open Source',
      tech_stack: [
        'Python', 'Tkinter', 'tkhtmlview', 'NLTK', 'Ollama (llama2/mistral)',
        'pygame', 'yt-dlp', 'markdown2', 'BeautifulSoup4',
        'NewsAPI', 'Wikipedia', 'arXiv', 'Wolfram Alpha',
      ],
      key_features: [
        'Three modes: Chat (local LLM), Search (live sources), AI+RAG (hybrid)',
        'NLTK intent detection routes each query to the most relevant source(s)',
        '10+ information sources with graceful fallback chains',
        'YouTube audio download and playback via yt-dlp + pygame',
        'Markdown-to-HTML rendering with clickable links',
        'Threaded I/O — search and audio run without blocking the UI',
      ],
      results: {
        sources_integrated: '10+',
        modes: ['Chat', 'Search', 'AI+RAG'],
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/QuerySynth',
      },
    },
    {
      id: '05',
      tier: 'strong_sde',
      name: 'Tapestra — Interactive NLP Concept Mapping',
      tagline:
        'A Streamlit web app that turns text paragraphs into interactive directed concept graphs using TF-IDF, cosine similarity, PageRank, and Dijkstra\'s shortest path — with physics-based visualisation controls.',
      one_liner: 'Paste any text; see how its ideas connect, which ones matter most, and in what order to read them.',
      category: ['NLP', 'Graph Algorithms', 'Web'],
      period: 'Dec 2024 – Jan 2025',
      team_size: 1,
      type: 'Solo · Live Deployment',
      tech_stack: [
        'Python 3.8+', 'Streamlit', 'NLTK', 'scikit-learn',
        'NetworkX (PageRank, Dijkstra)', 'PyVis', 'Streamlit Community Cloud',
      ],
      key_features: [
        'Paragraph-by-paragraph directed concept graphs from sentence similarity',
        'PageRank node scoring — most semantically central sentences are largest nodes',
        'Dijkstra shortest-path optimal reading order table',
        'Per-graph physics controls: spring length, spring constant, gravity',
        'Download any graph as standalone HTML file',
        'Live deployment on Streamlit Community Cloud — zero installation',
      ],
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Tapestra',
        live_app: 'https://tapestra-jzh6yjyhlhcs5r8xtxwjtz.streamlit.app/',
      },
    },
    {
      id: '06',
      tier: 'strong_sde',
      name: 'ML Attack Pipeline for XOR-Arbiter PUF',
      tagline:
        'An 85-dimensional polynomial feature pipeline that models XOR-Arbiter PUF challenge-response behaviour with a linear SVM, achieving 100% accuracy in 0.243 seconds — a 25× speedup over equivalent L1-penalised variants.',
      one_liner: 'Derived a polynomial feature map from hardware security equations; proved a linear classifier is all it takes to break the system — in under a quarter of a second.',
      category: ['ML', 'Hardware Security', 'Feature Engineering'],
      period: 'Mar 2025 – Apr 2025',
      team_size: 6,
      tech_stack: ['Python 3.8+', 'NumPy', 'scikit-learn (LinearSVC, RidgeClassifier)', 'pandas'],
      key_features: [
        'Mathematically derived 85-D feature map from XOR-PUF delay differential equations',
        'Variance filter removing near-constant features',
        'Comprehensive hyperparameter study: 7 LinearSVC configs, 6 RidgeClassifier configs',
        'Optimised configuration: tol=1e-2 gives 25× speedup at identical 100% accuracy',
      ],
      results: {
        accuracy: '100%',
        train_time_seconds: 0.243,
        speedup_over_l1: '25×',
        feature_dimensions: 85,
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/ML-PUF',
      },
    },
    {
      id: '07',
      tier: 'strong_sde',
      name: 'Anuvidhi Natipher — Multilingual Video Dubbing',
      tagline:
        'A Streamlit web app that fully automates video dubbing into 17 languages — extracting audio, transcribing, translating, synthesising dubbed speech with time-stretching, generating SRT subtitles, and syncing the new audio back.',
      one_liner: 'Upload a video, pick a language — the app handles the rest, including keeping the audio in sync.',
      category: ['Audio/Video', 'NLP', 'Web'],
      period: 'Jun 2024 – Jul 2024',
      team_size: 1,
      type: 'Solo · Live Deployment',
      tech_stack: ['Python', 'Streamlit', 'PyDub', 'FFmpeg', 'SpeechRecognition', 'deep-translator', 'gTTS', 'NumPy'],
      languages_supported: ['Hindi', 'Bengali', 'Gujarati', 'Kannada', 'Malayalam', 'Marathi', 'Tamil', 'Telugu', 'Spanish', 'French', 'German'],
      key_features: [
        '17 supported languages (10 Indian regional languages)',
        'Silence-based audio segmentation for natural sentence-level dubbing',
        'Time-stretching preserves original video timing — no sync drift',
        'Automatic SRT subtitle generation with per-segment timestamps',
        'Cross-platform FFmpeg integration with fallback handling',
      ],
      results: {
        languages_supported: 17,
        indian_languages: 10,
        deployment: 'Live on Streamlit Community Cloud',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Anuvidhi-Natipher',
        live_app: 'https://anuvidhinatipher-cpbczhdprr2pzuglzzcmwp.streamlit.app/',
      },
    },
    {
      id: '08',
      tier: 'strong_sde',
      name: 'Spaced Repetition — Memory Palace System',
      tagline:
        'A minimal, zero-dependency vanilla JS spaced repetition tracker preloaded with 114 Chemical Engineering concepts, designed around a Memory Palace workflow with priority-formula scheduling and JSON export/import.',
      one_liner: 'A zero-install, always-available complement to the VR Memory Palace — review concepts on any device, no headset required.',
      category: ['Frontend', 'EdTech', 'Vanilla JS'],
      period: 'Mar 2026 – May 2026',
      team_size: 1,
      type: 'Solo · Live on GitHub Pages',
      tech_stack: ['HTML', 'CSS (custom, no frameworks)', 'Vanilla JavaScript', 'LocalStorage API', 'GitHub Pages'],
      key_features: [
        '114 preloaded Chemical Engineering concepts across thermodynamics, mass balances, phase equilibria',
        'Memory object mapping (each concept linked to its VR palace anchor object)',
        'Priority formula: priority = strength − (repetitions × 0.5)',
        'Easy (+2) / Medium (+1) / Tough (−2) recall buttons',
        'JSON export/import for progress backup and cross-device transfer',
        'Zero dependencies, zero install — opens instantly from GitHub Pages URL',
      ],
      results: {
        concepts: 114,
        dependencies: 0,
        deployment: 'GitHub Pages (live)',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/SpacedRepetition',
        live_app: 'https://aadityaamlan-panda.github.io/SpacedRepetition/',
      },
    },
    {
      id: '09',
      tier: 'domain_engineering',
      name: 'Macroeconomic Analysis: Oil Price Supply-Side Shock',
      tagline:
        'A unified theoretical + empirical analysis of oil-price supply shocks across 7 historical episodes, combining AS-AD / IS-LM framework derivations with a Python FRED data pipeline and a fully structured LaTeX research report.',
      category: ['Economics', 'Data Pipeline', 'Research'],
      period: 'Mar 2026 – May 2026',
      course: 'ECO231 Course Project',
      team_size: 1,
      tech_stack: ['Python', 'pandas', 'NumPy', 'Matplotlib', 'FRED API', 'LaTeX'],
      key_features: [
        '9 FRED macroeconomic series: DCOILWTICO, CPIAUCSL, UNRATE, FEDFUNDS, GDPC1',
        '7 historical episodes: 1973-74 OPEC, 1979 Iran Revolution, 1990-91, 2007-08 GFC spike, 2020-22 COVID',
        'Modular framework: separate modules for AS-AD, IS-LM monetary/investment channels',
        '14-section LaTeX research report with theoretical and empirical figures',
      ],
      results: {
        episodes_covered: 7,
        fred_series: 9,
        report_sections: 14,
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Macroeconomic_Analysis_Oil_Price',
      },
    },
    {
      id: '10',
      tier: 'domain_engineering',
      name: 'Ethyl Benzene Process Optimisation',
      tagline:
        'Full-scale industrial EB plant simulation in Aspen Plus with 47.6% TAC reduction via sequential sensitivity analysis + MATLAB fmincon optimisation, and 9 tuned PID controllers maintaining 99.9% product purity under ±10% disturbances.',
      category: ['Chemical Engineering', 'Process Simulation', 'Control Systems'],
      period: 'Mar 2025 – Apr 2025',
      course: 'CHE352 Simulation Lab, Prof. Nitin Kaistha',
      team_size: 1,
      tech_stack: ['Aspen Plus', 'MATLAB (fmincon)', 'MATLAB Simulink', 'Fortran'],
      key_features: [
        'Complete industrial EB flowsheet: 2 CSTRs + 3 distillation columns + heat integration',
        '4-stage sequential sensitivity analysis reducing energy from 3,690 kW → 3,483 kW',
        'MATLAB fmincon 3-variable TAC optimisation: TAC $3.29M → $1.72M/year (47.6% reduction)',
        '9 PID controllers tuned with Ziegler-Nichols and Tyreus-Luyben',
        'Disturbance rejection: ±10% feed flow and ±4% composition perturbations',
      ],
      results: {
        tac_initial: '$3.29M/year',
        tac_final: '$1.72M/year',
        tac_reduction_pct: '47.6%',
        product_purity: '99.9+ mol% EB',
        pid_controllers: 9,
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/EthylBenzene-Production-Optimisation',
      },
    },
    {
      id: '11',
      tier: 'domain_engineering',
      name: 'Methyl Benzoate Process Design — ChE Capstone',
      tagline:
        'Full industrial process design for Methyl Benzoate via esterification in Aspen Plus: PFR with recycle, 4-column distillation, TEMA shell-and-tube heat exchanger, HEN via pinch analysis, Rankine cogeneration (~16,618 kW), and $64.6M annual profit.',
      category: ['Chemical Engineering', 'Process Design', 'Capstone'],
      period: 'Aug 2025 – Dec 2025',
      course: 'CHE453 Course Project, Prof. Raghavendra Ragipani',
      team_size: 8,
      tech_stack: ['Aspen Plus (UNIQUAC thermodynamics)', 'Aspen EDR', 'Fortran', 'LaTeX'],
      key_features: [
        'PFR (L=40m, D=8m, isothermal at 63.4°C): 99.63% overall conversion with recycle',
        'UNIQUAC thermodynamics validated against NIST Txy data for Water-Methanol binary',
        '4-column distillation train (C1: light ends, C2: MeOH recycle, C3: MEB product, C4: BA/PA)',
        'Pinch analysis (ΔTmin=10°C, 5 exchangers, no pinch point)',
        'Rankine cogeneration: HP+MP+LP+LLP = ~16,618 kW total',
      ],
      results: {
        overall_conversion: '99.63%',
        annual_profit: '$64.6M',
        total_capital_cost: '$29.8M',
        payback_period_years: '~3',
        cogeneration_kw: 16618,
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/ChE_Capstone_Project',
      },
    },
    {
      id: '12',
      tier: 'domain_engineering',
      name: 'Bacterial Chemotaxis — Keller-Segel MATLAB Suite',
      tagline:
        '38+ MATLAB scripts implementing the full Keller-Segel PDE framework for bacterial chemotaxis — covering explicit/implicit FD, Method of Lines, similarity transforms, BVP solvers, and grid-independence verification.',
      category: ['Numerical Methods', 'Computational Biology', 'MATLAB'],
      period: 'Oct 2024 – Nov 2024',
      course: 'CHE497 Undergraduate Project, Prof. Akash Choudhary',
      team_size: 1,
      tech_stack: ['MATLAB R2018a+', 'ode45', 'ode78', 'ode15s', 'bvp4c', 'pdepe', 'lsqnonlin'],
      key_features: [
        '38+ MATLAB scripts covering all major PDE discretisation strategies',
        'Explicit FD (central, upwind) and Implicit FD schemes',
        'Method of Lines with ode45/ode78 adaptive solvers',
        'Similarity transform reducing PDE to ODE solved with bvp4c',
        'Grid independence studies confirming convergence',
      ],
      results: {
        scripts: '38+',
        discretisation_methods: 'Explicit FD, Implicit FD, PDEPE, Method of Lines, BVP',
        ode_solvers: 'ode45, ode78, ode15s, bvp4c',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Chemotaxis-Keller-Segel',
      },
    },
    {
      id: '13',
      tier: 'domain_engineering',
      name: 'Three-Tank Control System Optimisation',
      tagline:
        'PID numerical optimisation achieving IAE=2.4557 on a third-order three-tank cascade — 4× better than best classical PI, with 84% IAE improvement through targeted proportional gain amplification.',
      category: ['Process Control', 'MATLAB', 'Optimisation'],
      period: 'Oct 2024 – Nov 2024',
      course: 'CHE381 Course Project, Prof. Ishan Bajaj',
      team_size: 1,
      tech_stack: ['MATLAB', 'Simulink'],
      key_features: [
        'Numerically optimised PID: Kc=15, τᵢ=191.822s, τᴅ=2s → IAE=2.4557',
        'Comparison against Ziegler-Nichols (IAE=23.66), Skogestad IMC (IAE=56.63)',
        '84% IAE improvement over Skogestad IMC via 8× proportional gain amplification',
        '4× performance over best classical PI',
      ],
      results: {
        optimised_iae: '2.4557',
        vs_best_classical_pi: '4× better',
        skogestad_improvement_pct: '84%',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Three-NonInt-Tanks',
      },
    },
    {
      id: '14',
      tier: 'domain_engineering',
      name: 'McCabe-Thiele Distillation Analysis',
      tagline:
        'MATLAB implementation of McCabe-Thiele graphical distillation design for a multi-section column with side stream withdrawal — VLE curve fitting, operating line construction, reflux optimisation, and automated tray counting.',
      category: ['Chemical Engineering', 'MATLAB', 'Process Design'],
      period: 'Mar 2024 – Apr 2024',
      course: 'CHE213 Course Project, Prof. Soumik Das',
      team_size: 1,
      tech_stack: ['MATLAB', 'Optimization Toolbox (lsqcurvefit, fsolve)'],
      key_features: [
        'VLE fitting: lsqcurvefit on experimental data',
        'Material balance solved with fsolve for D, W flowrates',
        '3-section operating lines (above side-stream, between side and feed, below feed)',
        'Automated McCabe-Thiele stage stepping',
      ],
      results: {
        ideal_trays: '~15-20 stages',
        reflux_ratio: '2.5 × Rmin',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/McCabe-Thiele',
      },
    },
    {
      id: '15',
      tier: 'domain_engineering',
      name: 'Profitability Analysis of a Manufacturing Plant',
      tagline:
        'A modular Python CLI for SOYD/DDB depreciation, discounted cash flow forecasting, NPV/IRR/payback computation, and interactive financial visualisation dashboards.',
      category: ['Financial Modelling', 'Python', 'ChE Economics'],
      period: 'Mar 2025 – Apr 2025',
      course: 'CHE352 Course Project, Prof. Nitin Kaistha',
      team_size: 1,
      tech_stack: ['Python 3.9+', 'NumPy', 'Matplotlib', 'pandas'],
      key_features: [
        'SOYD and DDB depreciation with customisable asset life and salvage value',
        'DCF forecasting: NPV, IRR (DCFROR), payback period, after-tax cash flows',
        'NPV sensitivity to discount rate (irr_scan over configurable range)',
      ],
      results: {
        sample_output: 'NPV: $125,847 | DCFROR: 15.82% | PBP: 4.2 years | ROI: 24.5%',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/Profitability-Analysis-Manufacturing-Plant',
      },
    },
    {
      id: '16',
      tier: 'domain_engineering',
      name: 'Methylene Blue Photodegradation — Kinetics Study',
      tagline:
        'Spectrophotometric kinetic study determining that MB photodegradation order shifts from first to zeroth order as H₂O₂ concentration decreases — validated across three experimental scenarios with R² evaluation.',
      category: ['Chemical Engineering', 'Experimental', 'Kinetics'],
      period: 'Oct 2024 – Nov 2024',
      course: 'CHE331 Course Project, Prof. Raj Ganesh S. Pala',
      team_size: 4,
      tech_stack: ['MATLAB', 'Python', 'UV Spectrophotometry'],
      key_features: [
        'Three MB:H₂O₂ molar ratios: 10:1, 29:1, 0 (no H₂O₂)',
        'Argon lamp photoreactor; UV spectrometer: absorbance measured every minute',
        'Finding: reaction order shifts from first (low H₂O₂) to zeroth (high/no H₂O₂)',
      ],
      results: {
        best_r_squared: '0.9329',
        finding: 'First-order → Zeroth-order transition as H₂O₂ decreases',
      },
    },
    {
      id: '17',
      tier: 'domain_engineering',
      name: 'ChemiEvolve Industries — Feasibility Analysis',
      tagline:
        'Multi-product chemical industry feasibility study designing industrial processes for three chemicals with reactor sizing, economic analysis, and EHS compliance.',
      category: ['Chemical Engineering', 'Process Design', 'Economics'],
      period: 'Mar 2024 – Apr 2024',
      course: 'CHE261 Course Project, Prof. Raghavendra Ragipani',
      team_size: 14,
      role: 'CEO of ChemiEvolve Industries — overall coordination, economic analysis, final report integration.',
      tech_stack: ['Aspen Plus', 'Python', 'Economic Analysis'],
      products: ["2'-13C-L-Histidine", 'Diphenic Acid', 'Phenol-Formaldehyde Resin (Bakelite)'],
      key_features: [
        'Reactor sizing: 578L formaldehyde reactor, 950L + 1400L Diphenic Acid reactors, 1300L Bakelite CSTR',
        'Diphenic Acid: diazotisation route (yield 88-91%) vs oxidation route (60-67%)',
        'Bakelite: condensation polymerisation, 3-stage cure (A → B → C), ammonia catalyst',
        'Capital investment planning: ~$50,000; production capacity up to 1,000 kg/day',
      ],
      results: {
        diphenic_acid_margin: '₹2,285/kg',
        bakelite_margin: '₹252/kg',
        capital_investment: '~$50,000',
      },
      links: {
        github: 'https://github.com/Aadityaamlan-Panda/ChemiEvolve-Industries-IITK',
      },
    },
  ],

  achievements: {
    academic: [
      {
        award: 'Ajai Agarwal Memorial Prize',
        description:
          'Conferred by the Director of IIT Kanpur to the best fourth-year undergraduate student in Chemical Engineering.',
        year: 'January 2026',
        institution: 'IIT Kanpur',
      },
      {
        award: 'Aedunuthula Prasad Memorial Scholarship',
        description: 'Awarded for the highest CPI at the end of the 6th semester in Chemical Engineering.',
        year: 'December 2025',
        institution: 'IIT Kanpur',
      },
      {
        award: 'Arakere and Karen Vasudev Scholarship',
        description: 'Awarded for the highest CPI among 110 students at the end of the 2nd year in Chemical Engineering.',
        year: 'July 2025',
        institution: 'IIT Kanpur',
      },
      {
        award: 'Academic Excellence Award',
        description: 'Recognises the top 10% academic performers at IIT Kanpur — awarded three consecutive years.',
        years: ['2022-23', '2023-24', '2024-25'],
        institution: 'IIT Kanpur',
      },
      {
        award: 'Pratibha Scholarship',
        description: 'Merit scholarship by Aditya Birla Group for outstanding academic performance — awarded three consecutive years.',
        years: ['2022-23', '2023-24', '2024-25'],
        institution: 'Aditya Birla Group',
      },
      {
        award: 'JEE Advanced 2022',
        description: 'All India Rank 4429 among 200,000+ qualified candidates.',
        year: '2022',
        rank: 4429,
      },
    ],
    creative_literary: [
      {
        award: 'Suryodaya Youth Icon Award',
        description: 'International Youth Icon Award 2022-23 from Suryodaya Literary Foundation for contributions to literature.',
        year: 'August 2022',
        institution: 'Suryodaya Literary Foundation',
      },
      {
        award: 'International Rank 7',
        description: 'Ranked 7th globally at the Storymirror World Writing Championship (W.W.C.) 2023.',
        year: '2023',
        institution: 'Storymirror',
      },
      {
        award: 'Scholarship for Excellence in English',
        description: 'Merit-based scholarship for outstanding performance in English language and literature.',
        year: 'August 2020',
        institution: 'British Council',
      },
      {
        award: '10 Co-authored International Anthologies',
        description:
          'Published across 10 international literary anthologies with Cleverfox Publishing, Notion Press, Kabita Minar, and Storymirror.',
        publications: [
          { title: 'Sand Castles and Paper Boats', publisher: 'Storymirror', link: 'https://www.flipkart.com/sand-castles-paper-boats/p/itm4c1369f91d047' },
          { title: 'Bliss', publisher: 'Cleverfox Publishing', link: 'https://www.amazon.in/Bliss-Sarbashis-Kumar-Paul/dp/9394457046' },
          { title: 'Inner Peace', publisher: 'Cleverfox Publishing' },
          { title: 'Efflorescence', publisher: 'Notion Press' },
          { title: 'Symphony of Words', publisher: 'Notion Press' },
          { title: 'Introspection', publisher: 'Cleverfox Publishing' },
          { title: 'Money, War and Peace', publisher: 'Cleverfox Publishing' },
          { title: 'Aruna', publisher: 'Kabita Minar' },
          { title: 'Exploring Life Through Poetry', publisher: 'Cleverfox Publishing' },
          { title: 'Polyphony of Women\'s Odyssey', publisher: 'Notion Press' },
        ],
      },
      {
        award: 'Sole Odia-to-English Translator',
        description:
          'The only Odia-to-English literary translation published in the inaugural issue of Matruakshar International Journal.',
        publication: 'Matruakshar International Journal, Vol. I, Issue I',
        translated_work: 'Paranani',
      },
    ],
    sports: [
      {
        award: 'Silver Medal',
        competition: 'Udghosh 2024',
        details: 'IIT Kanpur Sports Festival, Under-77 kg Weightlifting category',
        year: '2024',
      },
      {
        award: 'Silver Medal',
        competition: 'Kanpur District Weightlifting Competition 2024',
        details: 'Junior Division',
        year: '2024',
      },
      {
        award: 'Inter-IIT Representative',
        competition: '56th Inter-IIT Sports Meet',
        details: 'Mumbai, 2023',
        year: '2023',
      },
      {
        award: 'Inter-IIT Representative',
        competition: '57th Inter-IIT Sports Meet',
        details: 'Indore, 2024',
        year: '2024',
      },
    ],
  },

  creative_writing: {
    summary: 'A poet, writer, critic, and literary transliterator. 60+ poems, 4 stories, 8 articles, 1 translation. Published across 10 international anthologies.',
    github_repo: 'https://github.com/Aadityaamlan-Panda/CreativeWriting-AadityaamlanPanda',
    poetry_count: 60,
    articles_count: 8,
    stories_count: 4,
    selected_poems: [
      'A Letter to Myself',
      'Altruistic Being',
      'An Encomium to the Intrepid Victress',
      'Autumn: The Solemn Drop of Rhythmic Transformations',
      'Benign Boreas',
      'Cinerastasis (Neologism)',
      'Dreamcatcher (Acrostic)',
      'The Spirit of Nelumbo',
      'The Synapse of Sentience',
      'Psalm of the Earth',
    ],
    stories: [
      'Amalgamating the Animate Abode',
      'How I Met My Genius',
      'The Latent Ailment',
      'Zeitenwende: The Apocalypse',
    ],
    translations: [
      {
        title: 'Paranani',
        direction: 'Odia → English',
        published_in: 'Matruakshar International Journal, Vol. I, Issue I',
        note: 'Sole Odia-to-English translation in this issue',
      },
    ],
  },

  key_metrics: {
    cpi_iit_kanpur: '9.41/10',
    jee_advanced_air: 4429,
    academic_excellence_awards: 3,
    internship_prototypes_built: 18,
    hackathon_teams_enabled: '30+',
    rag_context_precision: 0.87,
    rag_context_recall: 0.75,
    vr_quiz_accuracy_gain_pp: 7.7,
    vr_response_time_reduction_pct: 60.8,
    eb_tac_reduction_pct: 47.6,
    pid_improvement_over_classical_pi: '4×',
    puf_model_train_time_seconds: 0.243,
    puf_speedup: '25×',
    financial_ml_accuracy: '>60%',
    published_anthologies: 10,
    poems_written: '60+',
    matlab_scripts_keller_segel: '38+',
    vr_concepts_encoded: 114,
    methyl_benzoate_annual_profit: '$64.6M',
    spring_boot_api_endpoints: 9,
  },
};

export default portfolioData;
